# Generated by Django 3.2.2 on 2021-05-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='image',
        ),
    ]
