# Generated by Django 3.2.2 on 2021-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='writer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
